### ISSUE TITLE
Build Error with 3.2.6 Dart

### ISSUE THREAD

**Issue by DerKleinePunk** [fuzzybinary/dart_shared_libray#11]
[build] D:\Projects\Privat\dart_shared_libray\src\isolate_setup.cpp(222,8): error C2660: "dart::bin::DFE::CompileAndReadScript": Funktion akzeptiert keine 7 Argumente 

I hope You Unterstand it in German.

https://github.com/dart-lang/sdk/commit/23109940e0c0e20b8c32fefb4a5d04c82316c64b#diff-b437e35aa82b9ca7f474a2f3709391c7b91195fc3f20e7c1853cc509f74d44ef

I don't Understand what this Change do. Sorry

**Comment by fuzzybinary** [comment]
It looks like #12 has the correct value, at least until we know more about what `embeded_sources` does.
