### ISSUE TITLE
Not an issue just questions :)

### ISSUE THREAD

**Issue by codethinki** [fuzzybinary/dart_shared_libray#15]
Is it possible to use this lib to export the flutter framebuffer? (if you know if you dont know then ig i'll have to find out myself)
How much delay do u have with calling the vm? Or does that depend entirely on the dart code?

thx for answers :)

**Comment by fuzzybinary** [comment]
No. Exporting the Flutter framebuffer would require customization of Flutter, not Dart.

I'm also not sure what you mean by "delay". The calls to `Dart_Invoke` are synchronous, so they'll take as long as the Dart code takes to execute.
